apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.currencyService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.currencyService.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.currencyService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.currencyService.name }}
    spec:
      terminationGracePeriodSeconds: 10

      securityContext:
        fsGroup: 2000
        runAsNonRoot: true

      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsUser: 1000

        image: {{ .Values.images.repository }}/{{ .Values.currencyService.name }}:{{ .Values.images.tag | default .Chart.AppVersion }}

        ports:
        - name: grpc
          containerPort: 7000

        env:
        - name: PORT
          value: "7000"
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"          

        # Настройки Readiness и Liveness проб
        readinessProbe:
          grpc:
            port: 7000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          grpc:
            port: 7000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5

        resources:
          {{- toYaml .Values.currencyService.resources | nindent 10 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.currencyService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.currencyService.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.currencyService.name }}
  ports:
  - name: grpc
    port: 7000
    targetPort: 7000
  