apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.recommendationService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.recommendationService.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.recommendationService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.recommendationService.name }}
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 2000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: {{ .Values.images.repository }}/{{ .Values.recommendationService.name }}:{{ .Values.images.tag | default .Chart.AppVersion }}
        ports:
        - name: grpc
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "{{ .Values.productCatalogService.name }}:3550"
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          grpc:
            port: 8080
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          grpc:
            port: 8080
        resources:
          {{- toYaml .Values.recommendationService.resources | nindent 12 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.recommendationService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.recommendationService.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.recommendationService.name }}
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
