apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.shippingService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.shippingService.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.shippingService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.shippingService.name }}
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 2000
      containers:
      - name: server
        image: {{ .Values.images.repository }}/{{ .Values.shippingService.name }}:{{ .Values.images.tag | default .Chart.AppVersion }}
        ports:
        - name: grpc
          containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          grpc:
            port: 50051
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          grpc:
            port: 50051
        resources:
          {{- toYaml .Values.shippingService.resources | nindent 12 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shippingService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.shippingService.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.shippingService.name }}
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
